name: Demo push with tags
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Lokalise
        uses: bodrovis/Lok-Actions/actions/push@master
        with:
          api_token: c430105f37c57b10e514a1cf86ac9f05d1d25b5f
          project_id: 5007330766e058e0bed4d3.26377346
          base_lang: en
          translations_path: locales
          file_format: po
          additional_params: "--convert-placeholders --hidden-from-contributors"
